# Generated by Django 3.2.12 on 2022-06-20 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('salon', models.Field(default=None)),
                ('user', models.Field(default=None)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('request_to_complete', 'Request To Complete'), ('completed', 'Completed')], default='new', max_length=32)),
                ('total_net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.Field(default=None)),
                ('price_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='api.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
